apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: work-pvc
  namespace: c503-br-3n-7
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 500Mi
  storageClassName: stc

---
apiVersion: v1
kind: Pod
metadata:
  name: upload-test-pod
  namespace: c503-br-3n-7
spec:
  containers:
    - name: app
      image: <your-registry>/<name>:ubi9-vi-python
      command: ["bash", "-lc", "sleep infinity"]
      volumeMounts:
        - name: work
          mountPath: /app
  volumes:
    - name: work
      persistentVolumeClaim:
        claimName: work-pvc
